/**
 * API schema exports.
 *
 * @packageDocumentation
 * @public
 */

// Common schemas
export {
  atUriSchema,
  didSchema,
  cidSchema,
  paginationQuerySchema,
  paginationResponseSchema,
  paginatedResponse,
  pdsSourceSchema,
  indexMetadataSchema,
  authorRefSchema,
  timestampQuerySchema,
  sortOrderSchema,
  searchQuerySchema,
  type PaginationQuery,
  type PDSSource,
  type AuthorRef,
  type SearchQueryParams,
} from './common.js';

// Error schemas
export {
  errorDetailSchema,
  errorResponseSchema,
  validationErrorSchema,
  authenticationErrorSchema,
  authorizationErrorSchema,
  notFoundErrorSchema,
  rateLimitErrorSchema,
  internalErrorSchema,
  commonErrorResponses,
  type ErrorResponseType,
} from './error.js';

// Eprint schemas
export {
  blobRefSchema,
  eprintMetricsSchema,
  fieldRefSchema,
  eprintSummarySchema,
  eprintResponseSchema,
  getSubmissionParamsSchema,
  listByAuthorParamsSchema,
  searchEprintsParamsSchema,
  eprintListResponseSchema,
  searchResultsResponseSchema,
  type EprintSummary,
  type EprintResponse,
  type GetSubmissionParams,
  type ListByAuthorParams,
  type SearchEprintsParams,
  type EprintListResponse,
  type SearchResultsResponse,
} from './eprint.js';

// Graph schemas
export {
  externalIdSchema,
  fieldStatusSchema,
  fieldNodeSchema,
  fieldRelationshipSchema,
  fieldDetailSchema,
  getFieldParamsSchema,
  authorityRecordSchema,
  searchAuthoritiesParamsSchema,
  authoritySearchResponseSchema,
  pmestFacetSchema,
  browseFacetedParamsSchema,
  facetValueSchema,
  facetedBrowseResponseSchema,
  fieldListResponseSchema,
  type ExternalId,
  type FieldNode,
  type FieldDetail,
  type GetFieldParams,
  type AuthorityRecord,
  type SearchAuthoritiesParams,
  type PMESTFacet,
  type BrowseFacetedParams,
  type FacetedBrowseResponse,
  type FieldListResponse,
} from './graph.js';

// Review schemas
export {
  annotationMotivationSchema,
  textSpanTargetSchema,
  annotationBodySchema,
  reviewSchema,
  reviewThreadSchema,
  listReviewsForEprintParamsSchema,
  getReviewThreadParamsSchema,
  createReviewInputSchema,
  deleteReviewInputSchema,
  reviewsResponseSchema,
  type AnnotationMotivation,
  type TextSpanTarget,
  type AnnotationBody,
  type Review,
  type ReviewThread,
  type ListReviewsForEprintParams,
  type GetReviewThreadParams,
  type CreateReviewInput,
  type DeleteReviewInput,
  type ReviewsResponse,
} from './review.js';

// Tag schemas
export {
  userTagSchema,
  tagSummarySchema,
  tagSuggestionSchema,
  listTagsForEprintParamsSchema,
  getTagSuggestionsParamsSchema,
  getTrendingTagsParamsSchema,
  searchTagsParamsSchema,
  getTagDetailParamsSchema,
  createTagInputSchema,
  deleteTagInputSchema,
  eprintTagsResponseSchema,
  tagSuggestionsResponseSchema,
  trendingTagsResponseSchema,
  tagSearchResponseSchema,
  type UserTag,
  type TagSummary,
  type TagSuggestion,
  type ListTagsForEprintParams,
  type GetTagSuggestionsParams,
  type GetTrendingTagsParams,
  type SearchTagsParams,
  type GetTagDetailParams,
  type CreateTagInput,
  type DeleteTagInput,
  type EprintTagsResponse,
  type TagSuggestionsResponse,
  type TrendingTagsResponse,
  type TagSearchResponse,
} from './tag.js';

// Endorsement schemas
export {
  contributionTypeSchema,
  endorsementSchema,
  endorsementSummarySchema,
  listEndorsementsForEprintParamsSchema,
  getEndorsementSummaryParamsSchema,
  getUserEndorsementParamsSchema,
  createEndorsementInputSchema,
  updateEndorsementInputSchema,
  deleteEndorsementInputSchema,
  endorsementsResponseSchema,
  type ContributionType,
  type Endorsement,
  type EndorsementSummary,
  type ListEndorsementsForEprintParams,
  type GetEndorsementSummaryParams,
  type GetUserEndorsementParams,
  type CreateEndorsementInput,
  type UpdateEndorsementInput,
  type DeleteEndorsementInput,
  type EndorsementsResponse,
} from './endorsement.js';

// Contribution type schemas (CRediT governance)
export {
  contributionMappingSystemSchema,
  semanticMatchTypeSchema,
  contributionExternalMappingSchema,
  contributionTypeStatusSchema,
  contributionTypeSchema as creditContributionTypeSchema,
  contributionTypeSummarySchema,
  listContributionTypesParamsSchema,
  listContributionTypesResponseSchema,
  getContributionTypeParamsSchema,
  contributionProposalTypeSchema,
  contributionProposalStatusSchema,
  proposalVoteTallySchema,
  contributionTypeProposalSchema,
  contributionProposalSummarySchema,
  listContributionProposalsParamsSchema,
  listContributionProposalsResponseSchema,
  getContributionProposalParamsSchema,
  searchContributionTypesParamsSchema,
  searchContributionTypesResponseSchema,
  type ContributionExternalMapping,
  type ContributionTypeResponse,
  type ContributionTypeSummary,
  type ListContributionTypesParams,
  type ListContributionTypesResponse,
  type GetContributionTypeParams,
  type ProposalVoteTally,
  type ContributionTypeProposalResponse,
  type ContributionProposalSummary,
  type ListContributionProposalsParams,
  type ListContributionProposalsResponse,
  type GetContributionProposalParams,
  type SearchContributionTypesParams,
  type SearchContributionTypesResponse,
} from './contribution.js';

// Discovery schemas
export {
  recommendationExplanationSchema,
  recommendedEprintSchema,
  relatedEprintSchema,
  citationSchema,
  enrichmentDataSchema,
  getRecommendationsParamsSchema,
  getRecommendationsResponseSchema,
  getSimilarParamsSchema,
  getSimilarResponseSchema,
  getCitationsParamsSchema,
  getCitationsResponseSchema,
  getEnrichmentParamsSchema,
  getEnrichmentResponseSchema,
  recordInteractionParamsSchema,
  recordInteractionResponseSchema,
  type RecommendationExplanation,
  type RecommendedEprint,
  type RelatedEprint,
  type Citation,
  type EnrichmentData,
  type GetRecommendationsParams,
  type GetRecommendationsResponse,
  type GetSimilarParams,
  type GetSimilarResponse,
  type GetCitationsParams,
  type GetCitationsResponse,
  type GetEnrichmentParams,
  type GetEnrichmentResponse,
  type RecordInteractionParams,
  type RecordInteractionResponse,
} from './discovery.js';
