/**
 * API schema exports.
 *
 * @packageDocumentation
 * @public
 */

// Common schemas
export {
  atUriSchema,
  didSchema,
  cidSchema,
  paginationQuerySchema,
  paginationResponseSchema,
  paginatedResponse,
  pdsSourceSchema,
  indexMetadataSchema,
  authorRefSchema,
  timestampQuerySchema,
  sortOrderSchema,
  searchQuerySchema,
  type PaginationQuery,
  type PDSSource,
  type AuthorRef,
  type SearchQueryParams,
} from './common.js';

// Error schemas
export {
  errorDetailSchema,
  errorResponseSchema,
  validationErrorSchema,
  authenticationErrorSchema,
  authorizationErrorSchema,
  notFoundErrorSchema,
  rateLimitErrorSchema,
  internalErrorSchema,
  commonErrorResponses,
  type ErrorResponseType,
} from './error.js';

// Preprint schemas
export {
  blobRefSchema,
  preprintMetricsSchema,
  fieldRefSchema,
  preprintSummarySchema,
  preprintResponseSchema,
  getSubmissionParamsSchema,
  listByAuthorParamsSchema,
  searchPreprintsParamsSchema,
  preprintListResponseSchema,
  searchResultsResponseSchema,
  type PreprintSummary,
  type PreprintResponse,
  type GetSubmissionParams,
  type ListByAuthorParams,
  type SearchPreprintsParams,
  type PreprintListResponse,
  type SearchResultsResponse,
} from './preprint.js';

// Graph schemas
export {
  externalIdSchema,
  fieldStatusSchema,
  fieldNodeSchema,
  fieldRelationshipSchema,
  fieldDetailSchema,
  getFieldParamsSchema,
  authorityRecordSchema,
  searchAuthoritiesParamsSchema,
  authoritySearchResponseSchema,
  pmestFacetSchema,
  browseFacetedParamsSchema,
  facetValueSchema,
  facetedBrowseResponseSchema,
  fieldListResponseSchema,
  type ExternalId,
  type FieldNode,
  type FieldDetail,
  type GetFieldParams,
  type AuthorityRecord,
  type SearchAuthoritiesParams,
  type PMESTFacet,
  type BrowseFacetedParams,
  type FacetedBrowseResponse,
  type FieldListResponse,
} from './graph.js';

// Review schemas
export {
  annotationMotivationSchema,
  textSpanTargetSchema,
  annotationBodySchema,
  reviewSchema,
  reviewThreadSchema,
  listReviewsForPreprintParamsSchema,
  getReviewThreadParamsSchema,
  createReviewInputSchema,
  deleteReviewInputSchema,
  reviewsResponseSchema,
  type AnnotationMotivation,
  type TextSpanTarget,
  type AnnotationBody,
  type Review,
  type ReviewThread,
  type ListReviewsForPreprintParams,
  type GetReviewThreadParams,
  type CreateReviewInput,
  type DeleteReviewInput,
  type ReviewsResponse,
} from './review.js';

// Tag schemas
export {
  userTagSchema,
  tagSummarySchema,
  tagSuggestionSchema,
  listTagsForPreprintParamsSchema,
  getTagSuggestionsParamsSchema,
  getTrendingTagsParamsSchema,
  searchTagsParamsSchema,
  getTagDetailParamsSchema,
  createTagInputSchema,
  deleteTagInputSchema,
  preprintTagsResponseSchema,
  tagSuggestionsResponseSchema,
  trendingTagsResponseSchema,
  tagSearchResponseSchema,
  type UserTag,
  type TagSummary,
  type TagSuggestion,
  type ListTagsForPreprintParams,
  type GetTagSuggestionsParams,
  type GetTrendingTagsParams,
  type SearchTagsParams,
  type GetTagDetailParams,
  type CreateTagInput,
  type DeleteTagInput,
  type PreprintTagsResponse,
  type TagSuggestionsResponse,
  type TrendingTagsResponse,
  type TagSearchResponse,
} from './tag.js';

// Endorsement schemas
export {
  contributionTypeSchema,
  endorsementSchema,
  endorsementSummarySchema,
  listEndorsementsForPreprintParamsSchema,
  getEndorsementSummaryParamsSchema,
  getUserEndorsementParamsSchema,
  createEndorsementInputSchema,
  updateEndorsementInputSchema,
  deleteEndorsementInputSchema,
  endorsementsResponseSchema,
  type ContributionType,
  type Endorsement,
  type EndorsementSummary,
  type ListEndorsementsForPreprintParams,
  type GetEndorsementSummaryParams,
  type GetUserEndorsementParams,
  type CreateEndorsementInput,
  type UpdateEndorsementInput,
  type DeleteEndorsementInput,
  type EndorsementsResponse,
} from './endorsement.js';

// Contribution type schemas (CRediT governance)
export {
  contributionMappingSystemSchema,
  semanticMatchTypeSchema,
  contributionExternalMappingSchema,
  contributionTypeStatusSchema,
  contributionTypeSchema as creditContributionTypeSchema,
  contributionTypeSummarySchema,
  listContributionTypesParamsSchema,
  listContributionTypesResponseSchema,
  getContributionTypeParamsSchema,
  contributionProposalTypeSchema,
  contributionProposalStatusSchema,
  proposalVoteTallySchema,
  contributionTypeProposalSchema,
  contributionProposalSummarySchema,
  listContributionProposalsParamsSchema,
  listContributionProposalsResponseSchema,
  getContributionProposalParamsSchema,
  searchContributionTypesParamsSchema,
  searchContributionTypesResponseSchema,
  type ContributionExternalMapping,
  type ContributionTypeResponse,
  type ContributionTypeSummary,
  type ListContributionTypesParams,
  type ListContributionTypesResponse,
  type GetContributionTypeParams,
  type ProposalVoteTally,
  type ContributionTypeProposalResponse,
  type ContributionProposalSummary,
  type ListContributionProposalsParams,
  type ListContributionProposalsResponse,
  type GetContributionProposalParams,
  type SearchContributionTypesParams,
  type SearchContributionTypesResponse,
} from './contribution.js';

// Discovery schemas
export {
  recommendationExplanationSchema,
  recommendedPreprintSchema,
  relatedPreprintSchema,
  citationSchema,
  enrichmentDataSchema,
  getRecommendationsParamsSchema,
  getRecommendationsResponseSchema,
  getSimilarParamsSchema,
  getSimilarResponseSchema,
  getCitationsParamsSchema,
  getCitationsResponseSchema,
  getEnrichmentParamsSchema,
  getEnrichmentResponseSchema,
  recordInteractionParamsSchema,
  recordInteractionResponseSchema,
  type RecommendationExplanation,
  type RecommendedPreprint,
  type RelatedPreprint,
  type Citation,
  type EnrichmentData,
  type GetRecommendationsParams,
  type GetRecommendationsResponse,
  type GetSimilarParams,
  type GetSimilarResponse,
  type GetCitationsParams,
  type GetCitationsResponse,
  type GetEnrichmentParams,
  type GetEnrichmentResponse,
  type RecordInteractionParams,
  type RecordInteractionResponse,
} from './discovery.js';
