/**
 * Shared test constants for web package tests.
 *
 * @remarks
 * These constants mirror the backend test constants to ensure consistency
 * across the monorepo.
 */

/**
 * Graph PDS DID for test fixtures.
 *
 * @remarks
 * All tests should use this consistent graph PDS DID to avoid
 * confusion and ensure tests work together.
 */
export const TEST_GRAPH_PDS_DID = 'did:plc:chive-governance';

/**
 * Test user DIDs for various test scenarios.
 */
export const TEST_USER_DIDS = {
  /** Primary test user */
  USER_1: 'did:plc:testuser1',
  /** Secondary test user */
  USER_2: 'did:plc:testuser2',
  /** Tertiary test user */
  USER_3: 'did:plc:testuser3',
  /** Admin test user */
  ADMIN: 'did:plc:testadmin',
  /** Author test user */
  AUTHOR: 'did:plc:testauthor123',
} as const;

/**
 * Build an AT-URI for a graph node.
 *
 * @param uuid - Node UUID
 * @returns Full AT-URI
 */
export function graphNodeUri(uuid: string): string {
  return `at://${TEST_GRAPH_PDS_DID}/pub.chive.graph.node/${uuid}`;
}

/**
 * Build an AT-URI for a graph proposal.
 *
 * @param id - Proposal ID
 * @returns Full AT-URI
 */
export function graphProposalUri(id: string): string {
  return `at://${TEST_GRAPH_PDS_DID}/pub.chive.graph.proposal/${id}`;
}

/**
 * Common test UUIDs for graph nodes.
 *
 * @remarks
 * These are deterministic UUIDs used across tests.
 * They match the UUIDs generated by seed scripts.
 */
export const TEST_NODE_UUIDS = {
  /** Conceptualization CRediT type */
  CONCEPTUALIZATION: 'e1612645-6a62-59b7-a13a-8d618637be85',
  /** Data Curation CRediT type */
  DATA_CURATION: 'fa5c6fc7-2202-5e45-8364-7740ae534f7c',
  /** Formal Analysis CRediT type */
  FORMAL_ANALYSIS: '8d456593-b60d-5544-8e1b-ac831b29267c',
  /** Investigation CRediT type */
  INVESTIGATION: '5d67f57c-9d4c-59e3-b3b1-d7205b33f6c8',
  /** Methodology CRediT type */
  METHODOLOGY: '052bfbce-9b15-55fd-8efc-99e82f7abeb2',
  /** Writing Original Draft CRediT type */
  WRITING_ORIGINAL_DRAFT: '829cce56-857a-5abb-be9d-9e6b29f51198',
  /** Machine Learning field */
  MACHINE_LEARNING: 'f39a6280-d70a-5e59-9022-1ce485cc5bf4',
  /** Neuroscience field */
  NEUROSCIENCE: '17c7f1fa-28cc-582e-a9fa-74de0d7bb636',
} as const;
