#!/bin/bash
# ==============================================================================
# Chive Environment Generator
# ==============================================================================
# Generates web/.env.local for the specified development mode.
#
# Usage:
#   ./scripts/generate-env.sh [local|tunnel] [tunnel_url]
#
# Arguments:
#   mode       - Development mode: "local" (default) or "tunnel"
#   tunnel_url - Tunnel URL (only used when mode is "tunnel")
#
# Examples:
#   ./scripts/generate-env.sh local
#   ./scripts/generate-env.sh tunnel https://abc123.ngrok.io
# ==============================================================================

set -e

MODE=${1:-local}
TUNNEL_URL=${2:-}
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"

# Determine OAuth URL based on mode
if [ "$MODE" = "tunnel" ] && [ -n "$TUNNEL_URL" ]; then
  OAUTH_URL="$TUNNEL_URL"
else
  # Use 127.0.0.1 (NOT localhost) for ATProto loopback compliance
  OAUTH_URL="http://127.0.0.1:3000"
fi

# Generate web/.env.local
cat > "$ROOT_DIR/web/.env.local" << EOF
# ==============================================================================
# Auto-generated by scripts/generate-env.sh
# Mode: $MODE | Generated: $(date)
# ==============================================================================
# DO NOT COMMIT THIS FILE - it's in .gitignore

# OAuth configuration
# ATProto requires 127.0.0.1 (NOT localhost) for loopback OAuth
NEXT_PUBLIC_OAUTH_BASE_URL=$OAUTH_URL

# Backend API URL
NEXT_PUBLIC_API_URL=http://127.0.0.1:3001

# Development mode (affects conditional headers)
NEXT_PUBLIC_DEV_MODE=$MODE
EOF

echo "✅ Generated web/.env.local"
echo "   OAUTH_BASE_URL: $OAUTH_URL"
echo "   API_URL: http://127.0.0.1:3001"
echo "   DEV_MODE: $MODE"
